'use client';

import { useState } from 'react';
import { ConfidenceIndicator } from './confidence-indicator';

interface NaturalLanguageSummaryProps {
  summary: string;
  confidence: number;
  technicalTerms?: Record<string, string>;
  className?: string;
}

export function NaturalLanguageSummary({
  summary,
  confidence,
  technicalTerms = {},
  className = '',
}: NaturalLanguageSummaryProps) {
  const [expandedTerm, setExpandedTerm] = useState<string | null>(null);
  const [showFullSummary, setShowFullSummary] = useState(false);

  // Split summary into paragraphs
  const paragraphs = summary.split('\n\n').filter((p) => p.trim());
  const shouldTruncate = paragraphs.length > 3 && !showFullSummary;
  const displayParagraphs = shouldTruncate ? paragraphs.slice(0, 3) : paragraphs;

  // Highlight technical terms in the text
  const highlightTerms = (text: string) => {
    if (Object.keys(technicalTerms).length === 0) {
      return text;
    }

    let highlightedText = text;
    Object.keys(technicalTerms).forEach((term) => {
      const regex = new RegExp(`\\b${term}\\b`, 'gi');
      highlightedText = highlightedText.replace(
        regex,
        `<span class="technical-term">${term}</span>`
      );
    });

    return highlightedText;
  };

  return (
    <div className={`${className}`}>
      <div className="flex items-start justify-between mb-4">
        <h3 className="text-lg font-semibold text-white">Executive Summary</h3>
        <ConfidenceIndicator confidence={confidence} size="small" showLabel />
      </div>

      <div className="prose prose-sm max-w-none">
        {displayParagraphs.map((paragraph, index) => (
          <div key={index} className="mb-4">
            <p
              className="text-slate-300 leading-relaxed"
              dangerouslySetInnerHTML={{
                __html: highlightTerms(paragraph),
              }}
              onClick={(e) => {
                const target = e.target as HTMLElement;
                if (target.classList.contains('technical-term')) {
                  const term = target.textContent || '';
                  setExpandedTerm(expandedTerm === term ? null : term);
                }
              }}
            />
          </div>
        ))}

        {shouldTruncate && (
          <button
            onClick={() => setShowFullSummary(true)}
            className="text-sm text-purple-400 hover:text-purple-300 font-medium"
          >
            Show more...
          </button>
        )}

        {showFullSummary && paragraphs.length > 3 && (
          <button
            onClick={() => setShowFullSummary(false)}
            className="text-sm text-purple-400 hover:text-purple-300 font-medium"
          >
            Show less
          </button>
        )}
      </div>

      {/* Technical Term Definition Popup */}
      {expandedTerm && technicalTerms[expandedTerm] && (
        <div className="mt-4 bg-blue-900/20 border border-blue-500/50 rounded-lg p-4">
          <div className="flex items-start justify-between">
            <div>
              <h4 className="text-sm font-semibold text-white mb-1">{expandedTerm}</h4>
              <p className="text-sm text-slate-300">{technicalTerms[expandedTerm]}</p>
            </div>
            <button
              onClick={() => setExpandedTerm(null)}
              className="text-slate-400 hover:text-slate-200"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
        </div>
      )}

      {/* Key Findings Callout */}
      <div className="mt-6 bg-blue-900/20 border border-blue-500/50 rounded-lg p-4">
        <div className="flex items-start space-x-3">
          <div className="flex-shrink-0">
            <svg
              className="w-6 h-6 text-blue-400"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </div>
          <div>
            <h4 className="text-sm font-semibold text-white mb-1">
              Understanding This Analysis
            </h4>
            <p className="text-sm text-slate-300">
              This summary is generated by AI based on analysis from multiple specialized agents.
              The confidence level indicates how certain the AI is about these findings. Click on
              highlighted terms to see their definitions.
            </p>
          </div>
        </div>
      </div>

      <style jsx>{`
        :global(.technical-term) {
          color: #a78bfa;
          text-decoration: underline;
          text-decoration-style: dotted;
          cursor: help;
        }
        :global(.technical-term:hover) {
          color: #c4b5fd;
          background-color: rgba(139, 92, 246, 0.1);
        }
      `}</style>
    </div>
  );
}
